### ISSUE TITLE
Not working on opera 12

### ISSUE THREAD

**Issue by loadletter** [loadletter/4chan-x#11]
Someone reported this, Presto opera versions don't seem to support MutationObserver, 4chan X 3.x and an handful of scripts try using window.OMutationObserver, but apart from those i haven't found any info on it, and i haven't been able to create one in the console on Opera 12.16.
RIP Opera presto.

![1396015398061](https://cloud.githubusercontent.com/assets/5257054/2631311/21432f4e-be57-11e3-85b7-0f19a9f8aa17.png)

**Comment by Kein** [comment]
Just dropping by to say thanks for Opera support. The only script that work properly on Opera 12.x and it is quite fast.
