### ISSUE TITLE
4chan-x broke when clearing entire firefox history

### ISSUE THREAD

**Issue by Davidj361** [loadletter/4chan-x#66]
Shortcuts aren't working and images don't expand when clicked. Sometimes the tab shows undefined in the title.

This started happening after I cleared my browser history of everything.

**Comment by Davidj361** [comment]
Deleted the script and reinstalled. The issues are stil persisting.

**Comment by ccd0** [comment]
4chan update broke it.  The bottom board list was removed and replaced with JS:
https://github.com/qqueue/4chan-JS/compare/abb81fe...3828a8c942

**Comment by Davidj361** [comment]
+1

**Comment by loadletter** [comment]
It should work with the new version, currently catalog links seems to be broken on firefox.
