### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by TwilightSkyline** [loadletter/4chan-x#70]
I feel like this might be a personal problem because I haven't seen any other posts about it, but a few people I know are also having the problem. If they haven't been added yet, they'd be great.

**Comment by loadletter** [comment]
Install this http://userscripts-mirror.org/scripts/show/87750
I've cleaned up a bit the readme

**Comment by TwilightSkyline** [comment]
Already using it. Thanks anyways.
Do you ever plan on implementing hyperlinks or will that add-on be the permanent fix?

**Comment by loadletter** [comment]
As longs as that script works I don't see why change
