### ISSUE TITLE
Flags on /pol/ not working properly

### ISSUE THREAD

**Issue by deathkiller666** [loadletter/4chan-x#72]
Flags load just fine when opening a thread, but whenever the autoupdater fetches a new post and the flag is not USA, then flag is not loaded properly for that post. It comes up as some weird Romanian ghost flag. Tried with latest Firefox and Opera 12.x. Possibly something to do with flags and ID? 

This is how it looks when fetching new non-american posts. 
![untitled](https://cloud.githubusercontent.com/assets/3485711/7729178/11b8ae80-ff1c-11e4-83b2-1742f43e450b.png)

**Comment by loadletter** [comment]
Reinstall to update it
https://github.com/loadletter/4chan-x/raw/master/4chan_x.user.js

**Comment by deathkiller666** [comment]
New posts no longer format the time to users local time on boards where there are flags. Happens on /sp/, /pol/ and /int/

![untitled](https://cloud.githubusercontent.com/assets/3485711/7747387/ac1189d8-ffc2-11e4-94ba-a8e4742696b2.png)

**Comment by deathkiller666** [comment]
I don't know if people get notified of new messages on closed issues. Just to be on the safe side. @loadletter

**Comment by loadletter** [comment]
> I don't know if people get notified of new messages on closed issues.

They do
