### ISSUE TITLE
Thread Watcher appears to be broken.

### ISSUE THREAD

**Issue by Patharg** [loadletter/4chan-x#74]
In 4chan X the heart icon next to the thread title does not appear. Instead, there is a broken link. Clicking said link does not add the thread to the thread watcher. This issue arises in Opera 12.17.

![untitled](https://cloud.githubusercontent.com/assets/13078764/8392967/460e265e-1cc9-11e5-9411-9fb797762586.png)

**Comment by loadletter** [comment]
I'll try giving it a look, meanwhile you can try using the "w" keybind

**Comment by Patharg** [comment]
That doesn't seem to work, either.

**Comment by loadletter** [comment]
Strange, I've tried it on opera 12.17 build 18xx and it worked fine, could you post your configuration?

**Comment by Patharg** [comment]
Sure. Here's a shot of the userscript folder.
![untitled](https://cloud.githubusercontent.com/assets/13078764/8432018/60fa1538-1f0b-11e5-8b76-7e4d54e9b6d8.png)

**Comment by loadletter** [comment]
Huh, if you installed it by copying it to the userscript folder, delete it, then
- Install [Violent monkey](https://addons.opera.com/en/extensions/details/violent-monkey/)
- Click on https://github.com/loadletter/4chan-x/raw/master/4chan_x.user.js

**Comment by Patharg** [comment]
That seems to have done the trick. Thanks!
