### ISSUE TITLE
Thread layout broken in Opera 12.xx

### ISSUE THREAD

**Issue by Kein** [loadletter/4chan-x#77]
![dasdas](https://cloud.githubusercontent.com/assets/623756/9522110/7692d4cc-4cdb-11e5-80e7-9297c1f22db5.jpg)
Latest git as of Aug27.

**Comment by loadletter** [comment]
![Opera 12.17 Build 1863](https://cloud.githubusercontent.com/assets/5257054/9577951/2bf95752-4fe6-11e5-87b2-ac2ed27f3523.png)
Strange, is it triggered by something?

**Comment by Kein** [comment]
No idea, it just there. Updated to latest git ans still same issue.

**Comment by ccd0** [comment]
It seems to happen for some people and not for others; I haven't figured out why.  See https://github.com/ccd0/4chan-x/issues/467 and https://boards.4chan.org/qa/thread/153855.  I've only been able to reproduce it for posts like https://boards.4chan.org/qa/thread/153855#p158828 in Blink.  I thought it might have been a browser change but if it's happening in Opera 12, it can't be that.

See if this CSS fixes it for you.  See http://www.opera.com/docs/usercss/ for how to add it in Opera 12.

    .replyContainer {
      display: table;
      margin: 2px 0px 4px;
    }
    .inline .replyContainer {
      margin: 0;
    }
    .replyContainer > div {
      display: table-cell !important;
    }
    div.sideArrows {
      float: none !important;
      vertical-align: top;
      padding: 0 2px;
    }

**Comment by Kein** [comment]
It does, thanks. Used "Easy CSS" ext for that. Cheers.

Weird issue tho, no idea what can cause it.

I have 4chan-x installed as UserJS directly, without any extensions' support. There are no other scripts used.
From extensions, I use:
- Adblok Plus
- Easy CSS
- rightImgur

**Comment by loadletter** [comment]
Should be ok now
