### ISSUE TITLE
Spoiler images and Dropdown

### ISSUE THREAD

**Issue by StingrayNine** [loadletter/4chan-x#84]
Reveal spoiler no longer works. Unknown for how long. The dropdown menu next to the post number also does nothing. Tested on chrome with Tampermonkey and only the script running.
No error messages and toggling/reloading does nothing
http://i.imgur.com/LSRYThb.png

**Comment by loadletter** [comment]
I've played around a bit with a clean setup of chrome/tampermonkey and similar 4chanx settings and it works fine.
I don't think it's caused by image servers being changed either.

Try backing up your settings, uninstalling/reinstalling 4chan X and then manually re-enabling the features you need

**Comment by StingrayNine** [comment]
I reinstalled 4chan X and it worked fine. Re-set my settings and it stopped. So I started tweaking around a bit and both the menu and spoiler-reveal breaks if you change the File Info Formatting from %l/%L to %n/%N. They both break at the same reload with all four permutations tested. Nothing else changed between reloads.

**Comment by StingrayNine** [comment]
After some more testing the menu/reveal only breaks on posts with images when the filename is not a link.
No clue why, but i'm sure you can look at it.

**Comment by loadletter** [comment]
Thanks for figuring it out, some stuff relied on the first element being an %l, you can try reinstalling it and importing your settings.

**Comment by StingrayNine** [comment]
works great. I noticed %p not working on revealed images in the filename-info. Is this also broken or just a side-effect?

**Comment by loadletter** [comment]
Possibly, I need to rewrite those things in a sane way

**Comment by StingrayNine** [comment]
This is fixed. Closing
