### ISSUE TITLE
4chan-x catalog no longer working

### ISSUE THREAD

**Issue by TheOvertNinja** [loadletter/4chan-x#90]
The script only seems to use the native catalog now without giving me the option to use the 4chan-x version.
Has the option been removed? I didn't see it in the patch notes.

**Comment by loadletter** [comment]
This version never had anything more than native catalog, you're probably confusing it with https://github.com/ccd0/4chan-x

**Comment by TheOvertNinja** [comment]
Ah, my bad. Totally got confused, thanks for the heads up.
